import fs from 'fs';
import path from 'path';

export interface ArchitectureMap {
  [key: string]: any;
}

/**
 * Call Ollama API to generate architecture map from indexed data with structured output
 */
async function generateArchitectureMapWithOllama(
  indexedData: any,
  systemPrompt: string,
  model: string = 'llama3.2'
): Promise<ArchitectureMap | null> {
  try {
    const prompt = `${systemPrompt}\n\n---INDEXED CODEBASE DATA---\n\n${JSON.stringify(indexedData, null, 2)}\n\n---END OF INDEXED DATA---\n\nNow generate a comprehensive architecture map based on the indexed data above.`;

    const response = await fetch('http://localhost:11434/api/generate', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        model: model,
        prompt: prompt,
        stream: false,
        format: 'json',
      }),
    });

    if (!response.ok) {
      throw new Error(`Ollama API error: ${response.statusText}`);
    }

    const data = await response.json();
    const result = JSON.parse(data.response);
    
    return result as ArchitectureMap;
  } catch (error) {
    console.error('Error generating architecture map:', error);
    return null;
  }
}

/**
 * Generate architecture map for a repository
 */
export async function generateArchitectureMap(
  repoPath: string,
  systemPrompt: string,
  model: string = 'llama3.2'
): Promise<{
  success: boolean;
  outputPath: string;
  data: ArchitectureMap;
}> {
  const indexPath = path.join(repoPath, '.codebase-index', 'index.json');

  // Check if index exists
  if (!fs.existsSync(indexPath)) {
    throw new Error('Repository not indexed. Please index the repository first.');
  }

  // Read indexed data
  const indexedData = JSON.parse(fs.readFileSync(indexPath, 'utf-8'));

  // Generate architecture map using AI
  console.log('Generating architecture map with AI...');
  const architectureData = await generateArchitectureMapWithOllama(indexedData, systemPrompt, model);

  if (!architectureData) {
    throw new Error('Failed to generate architecture map');
  }

  // Save the JSON file generated by AI
  const outputDir = path.join(repoPath, '.codebase-index');
  if (!fs.existsSync(outputDir)) {
    fs.mkdirSync(outputDir, { recursive: true });
  }

  const outputPath = path.join(outputDir, 'architecture.json');
  fs.writeFileSync(outputPath, JSON.stringify(architectureData, null, 2));

  return {
    success: true,
    outputPath: path.relative(process.cwd(), outputPath).replace(/\\/g, '/'),
    data: architectureData,
  };
}

/**
 * Get existing architecture map for a repository
 */
export function getArchitectureMap(repoPath: string): ArchitectureMap {
  const architecturePath = path.join(repoPath, '.codebase-index', 'architecture.json');

  if (!fs.existsSync(architecturePath)) {
    throw new Error('Architecture map not found. Please run mapping first.');
  }

  return JSON.parse(fs.readFileSync(architecturePath, 'utf-8'));
}
