import fs from 'fs';
import path from 'path';
import { ChatOllama } from '@langchain/ollama';
import { z } from 'zod';

export interface ArchitectureMap {
  framework: string;
  uiLayer: string;
  dbLayer: string;
  entryPoints: string[];
  apiRoutesFolder: string;
  authStrategy: string;
  styling: string;
  testing: string;
  folders: { [folderPath: string]: string };
  dependencies: { [packageName: string]: string };
}

/**
 * Call Ollama API using LangGraph with Zod structured output
 */
async function generateArchitectureMapWithOllama(
  indexedData: any,
  systemPrompt: string,
  model: string = 'llama3.2'
): Promise<ArchitectureMap | null> {
  try {
    // Create Ollama LLM instance
    const llm = new ChatOllama({
      model: model,
      temperature: 0.3,
      baseUrl: 'http://localhost:11434',
      format: 'json',
    });

    // Define Zod schema for architecture map
    const architectureMapSchema = z.object({
      framework: z.string(),
      uiLayer: z.string(),
      dbLayer: z.string(),
      entryPoints: z.array(z.string()),
      apiRoutesFolder: z.string(),
      authStrategy: z.string(),
      styling: z.string(),
      testing: z.string(),
      folders: z.record(z.string(), z.string()),
      dependencies: z.record(z.string(), z.string()),
    });

    // Create structured LLM with Zod schema
    const structuredLlm = llm.withStructuredOutput(architectureMapSchema);

    // Prepare the user message with indexed data
    const indexedJson = JSON.stringify(indexedData, null, 2);
    const userMessage = `---INDEXED CODEBASE DATA---\n\n${indexedJson}\n\n---END OF INDEXED DATA---\n\nGenerate a comprehensive architecture map based on the indexed data above.`;

    // Invoke LLM with structured output
    const result = await structuredLlm.invoke([
      { role: 'system', content: systemPrompt },
      { role: 'user', content: userMessage }
    ]);

    return result as ArchitectureMap;
  } catch (error) {
    console.error('Error generating architecture map:', error);
    return null;
  }
}

/**
 * Generate architecture map for a repository
 */
export async function generateArchitectureMap(
  repoPath: string,
  systemPrompt: string,
  model: string = 'llama3.2'
): Promise<{
  success: boolean;
  outputPath: string;
  data: ArchitectureMap;
}> {
  const indexPath = path.join(repoPath, '.codebase-index', 'index.json');

  // Check if index exists
  if (!fs.existsSync(indexPath)) {
    throw new Error('Repository not indexed. Please index the repository first.');
  }

  // Read indexed data
  const indexedData = JSON.parse(fs.readFileSync(indexPath, 'utf-8'));

  // Generate architecture map using AI
  console.log('Generating architecture map with AI...');
  const architectureData = await generateArchitectureMapWithOllama(indexedData, systemPrompt, model);

  if (!architectureData) {
    throw new Error('Failed to generate architecture map');
  }

  // Save the JSON file generated by AI
  const outputDir = path.join(repoPath, '.codebase-index');
  if (!fs.existsSync(outputDir)) {
    fs.mkdirSync(outputDir, { recursive: true });
  }

  const outputPath = path.join(outputDir, 'architecture.json');
  fs.writeFileSync(outputPath, JSON.stringify(architectureData, null, 2));

  return {
    success: true,
    outputPath: path.relative(process.cwd(), outputPath).replace(/\\/g, '/'),
    data: architectureData,
  };
}

/**
 * Get existing architecture map for a repository
 */
export function getArchitectureMap(repoPath: string): ArchitectureMap {
  const architecturePath = path.join(repoPath, '.codebase-index', 'architecture.json');

  if (!fs.existsSync(architecturePath)) {
    throw new Error('Architecture map not found. Please run mapping first.');
  }

  return JSON.parse(fs.readFileSync(architecturePath, 'utf-8'));
}
