import { NextRequest, NextResponse } from 'next/server';
import fs from 'fs';
import path from 'path';

// Load the repo mapping prompt
const PROMPTS_DIR = path.join(process.cwd(), 'prompts');
const REPO_MAPPING_PROMPT = fs.readFileSync(
  path.join(PROMPTS_DIR, 'repo-mapping.txt'), 
  'utf-8'
);

/**
 * Call Ollama API to generate architecture map from indexed data
 */
async function generateArchitectureMap(
  indexedData: any,
  model: string = 'llama3.2'
): Promise<any> {
  try {
    const response = await fetch('http://localhost:11434/api/generate', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        model: model,
        prompt: `${REPO_MAPPING_PROMPT}\n\n---INDEXED CODEBASE DATA---\n\n${JSON.stringify(indexedData, null, 2)}`,
        stream: false,
        format: 'json',
      }),
    });

    if (!response.ok) {
      throw new Error(`Ollama API error: ${response.statusText}`);
    }

    const data = await response.json();
    const result = JSON.parse(data.response);
    
    return result;
  } catch (error) {
    console.error('Error generating architecture map:', error);
    return null;
  }
}

/**
 * POST /api/map-repo
 * Request body: { repoName: string, model?: string }
 */
export async function POST(request: NextRequest) {
  try {
    const body = await request.json();
    const { repoName, model = 'llama3.2' } = body;

    if (!repoName) {
      return NextResponse.json(
        { error: 'repoName is required' },
        { status: 400 }
      );
    }

    const repoPath = path.join(process.cwd(), 'public', 'downloads', repoName);
    const indexPath = path.join(repoPath, '.codebase-index', 'index.json');

    // Check if repo exists
    if (!fs.existsSync(repoPath)) {
      return NextResponse.json(
        { error: `Repository not found: ${repoName}` },
        { status: 404 }
      );
    }

    // Check if index exists
    if (!fs.existsSync(indexPath)) {
      return NextResponse.json(
        { error: 'Repository not indexed. Please index the repository first.' },
        { status: 400 }
      );
    }

    // Read indexed data
    const indexedData = JSON.parse(fs.readFileSync(indexPath, 'utf-8'));

    // Generate architecture map using AI
    console.log('Generating architecture map with AI...');
    const architectureData = await generateArchitectureMap(indexedData, model);

    if (!architectureData) {
      return NextResponse.json(
        { error: 'Failed to generate architecture map' },
        { status: 500 }
      );
    }

    // Save the JSON file generated by AI
    const outputPath = path.join(repoPath, '.codebase-index', 'architecture.json');
    fs.writeFileSync(outputPath, JSON.stringify(architectureData, null, 2));

    return NextResponse.json({
      success: true,
      outputPath: path.relative(process.cwd(), outputPath).replace(/\\/g, '/'),
      data: architectureData,
    });

  } catch (error) {
    console.error('Error mapping repository:', error);
    return NextResponse.json(
      { error: 'Failed to map repository', details: String(error) },
      { status: 500 }
    );
  }
}

/**
 * GET /api/map-repo?repoName=xxx
 * Retrieve existing architecture map for a repository
 */
export async function GET(request: NextRequest) {
  try {
    const { searchParams } = new URL(request.url);
    const repoName = searchParams.get('repoName');

    if (!repoName) {
      return NextResponse.json(
        { error: 'repoName query parameter is required' },
        { status: 400 }
      );
    }

    const architecturePath = path.join(
      process.cwd(),
      'public',
      'downloads',
      repoName,
      '.codebase-index',
      'architecture.json'
    );

    if (!fs.existsSync(architecturePath)) {
      return NextResponse.json(
        { error: 'Architecture map not found. Please run POST /api/map-repo first.' },
        { status: 404 }
      );
    }

    const data = JSON.parse(fs.readFileSync(architecturePath, 'utf-8'));

    return NextResponse.json({
      success: true,
      data,
    });

  } catch (error) {
    console.error('Error retrieving architecture map:', error);
    return NextResponse.json(
      { error: 'Failed to retrieve architecture map', details: String(error) },
      { status: 500 }
    );
  }
}
